import os

COORDINATOR_URL = os.getenv(
    "COORDINATOR_URL",
    "http://localhost:8000"
)

HEARTBEAT_INTERVAL_SECONDS = int(
    os.getenv(
        "HEARTBEAT_INTERVAL_SECONDS",
        "10"
    )
)
TASK_POLL_INTERVAL_SECONDS = int(
    os.getenv(
        "TASK_POLL_INTERVAL_SECONDS",
        "5"
    )
)
WORKER_VERSION = "1.0.0"

REGISTRATION_INITIAL_DELAY_SECONDS = 1
REGISTRATION_MAX_DELAY_SECONDS = 60
REGISTRATION_JITTER_FACTOR = 0.2

METRICS_INTERVAL_SECONDS = 30