services:
  postgres:
    image: postgres:17

    container_name: fedforge-postgres

    environment :
      POSTGRES_DB: fedforge
      POSTGRES_USER : fedforge
      POSTGRES_PASSWORD : fedforge

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: